name: branch-deploy

on:
  issue_comment:
    types: [ created ]

# Permissions needed for reacting and adding comments for IssueOps commands
permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read

jobs:
  deploy:
    name: deploy
    if: ${{ github.event.issue.pull_request }} # only run on pull request comments
    runs-on: ubuntu-latest
    environment: production-secrets

    steps:
      - name: branch-deploy
        id: branch-deploy
        uses: github/branch-deploy@v5.2.0
        with:
          admins: the-hideout/core-contributors
          admins_pat: ${{ secrets.BRANCH_DEPLOY_ADMINS_PAT }}
          environment_targets: production

      - name: checkout
        if: steps.branch-deploy.outputs.continue == 'true'
        uses: actions/checkout@v3.5.2
        with:
          ref: ${{ steps.branch-deploy.outputs.ref }}

      # check the node version from the .node-version file
      - name: fetch node version
        if: steps.branch-deploy.outputs.continue == 'true'
        id: node-version
        run: |
          version=$(cat .node-version)
          echo "version=${version}" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v3.6.0
        if: steps.branch-deploy.outputs.continue == 'true'
        with:
          node-version: ${{ steps.node-version.outputs.version }}
          cache: 'npm'

      - name: install dependencies
        if: steps.branch-deploy.outputs.continue == 'true'
        run: npm install

      - name: register slash commands
        if: steps.branch-deploy.outputs.continue == 'true'
        env:
          NODE_ENV: ci
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
        run: node deploy-commands.mjs

      - name: deploy to railway
        if: steps.branch-deploy.outputs.continue == 'true'
        run: npm run deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
