name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3

      # validate JSON and YAML files
      - name: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v2.0.0
        with:
          comment: "true"
          exclude_file: ".github/config/exclude.txt"

      - uses: actions/setup-node@v3.7.0
        with:
          node-version-file: .node-version
          cache: 'npm'

      - name: Install
        run: npm ci

      # TODO add tests here
