name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: deployment check
        uses: github/branch-deploy@v9.1.1
        id: deployment-check
        with:
          merge_deploy_mode: "true" # tells the Action to use the merge commit workflow strategy
          environment: production

      # always run checkout because the 'release (sentry)' step needs the code
      - name: checkout
        uses: actions/checkout@v4.1.2

      - uses: actions/setup-node@v4.0.2
        if: ${{ steps.deployment-check.outputs.continue == 'true' }}
        with:
          node-version-file: .node-version
          cache: 'npm'

      - name: install dependencies
        if: ${{ steps.deployment-check.outputs.continue == 'true' }}
        run: npm install

      - name: register slash commands
        if: ${{ steps.deployment-check.outputs.continue == 'true' }}
        env:
          NODE_ENV: ci
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
        run: node deploy-commands.mjs

      - name: deploy to railway
        if: ${{ steps.deployment-check.outputs.continue == 'true' }}
        run: npm run deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: create sentry release
        uses: getsentry/action-release@e769183448303de84c5a06aaaddf9da7be26d6c7 # pin@v1.7.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: tarkov-dev
          SENTRY_PROJECT: stash
        with:
          environment: production
