name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: deployment check
        uses: github/branch-deploy@v5.2.0
        id: deployment-check
        with:
          merge_deploy_mode: "true" # tells the Action to use the merge commit workflow strategy
          environment: production

      - name: checkout
        if: ${{ steps.deployment-check.outputs.continue == 'true' }} # only run if the Action returned 'true' for the 'continue' output
        uses: actions/checkout@v3.5.2

      # check the node version from the .node-version file
      - name: fetch node version
        id: node-version
        run: |
          version=$(cat .node-version)
          echo "version=${version}" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ steps.node-version.outputs.version }}
          cache: 'npm'

      - name: install dependencies
        if: ${{ steps.deployment-check.outputs.continue == 'true' }}
        run: npm install

      - name: register slash commands
        if: ${{ steps.deployment-check.outputs.continue == 'true' }}
        env:
          NODE_ENV: ci
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
        run: node deploy-commands.mjs

      - name: deploy to railway
        if: ${{ steps.deployment-check.outputs.continue == 'true' }}
        run: npm run deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: create sentry release
        uses: getsentry/action-release@586b62368d564f25d694ce05fcb9cf53de65ac4f # pin@v1.3.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: tarkov-dev
          SENTRY_PROJECT: stash
        with:
          environment: production
