name: new pull request

on:
  pull_request:
    branches: [ main ]

jobs:
  new-pr:
    permissions:
      pull-requests: write
      contents: read

    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest

    steps:
      # Comment on new PR requests with deployment instructions
      - name: checkout
        uses: actions/checkout@v4.1.1
      - name: comment
        uses: GrantBirki/comment@e6bf4bc177996c9572b4ddb98b25eb1a80f9abc9 # pin@v2.0.7
        continue-on-error: true
        with:
          file: .github/new-pr-comment.md
