name: new pull request

on:
  pull_request:
    branches: [ main ]

jobs:
  new-pr:
    permissions:
      pull-requests: write
      contents: read

    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest

    steps:
      # Comment on new PR requests with deployment instructions
      - name: checkout
        uses: actions/checkout@v3.5.2
      - name: comment
        uses: GrantBirki/comment@1e9986de26cf23e6c4350276234c91705c540fef # pin@v2.0.3
        continue-on-error: true
        with:
          file: .github/new-pr-comment.md
