name: new pull request

on:
  pull_request:
    branches: [ main ]

jobs:
  new-pr:
    permissions:
      pull-requests: write
      contents: read

    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest

    steps:
      # Comment on new PR requests with deployment instructions
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: comment
        uses: GrantBirki/comment@f524ee31407667c05061bad41e1758b40298bd82 # pin@v2.1.0
        continue-on-error: true
        with:
          file: .github/new-pr-comment.md
